trying for real

diff --git a/pmovie/pmov2traj b/pmovie/pmov2traj
--- a/pmovie/pmov2traj
+++ b/pmovie/pmov2traj
@@ -91,6 +91,15 @@ if [ ! -n "$NPROCS" ]; then
 fi
 #executing
 export PMOVDIR=$DEST
-firsthash >> $LOGFILE 2>&1  || (echo "failed at firsthash"  && exit -1)
-scanp4    >> $LOGFILE 2>&1  || (echo "failed during scanp4" && exit -1)
-search    >> $LOGFILE 2>&1  || (echo "failed during search" && exit -1)
+if ! firsthash >> $LOGFILE 2>&1; then
+    echo "failed at firsthash"
+    exit -1
+fi
+if ! scanp4    >> $LOGFILE 2>&1; then
+    echo "failed during scanp4"
+    exit -1
+fi
+if ! search    >> $LOGFILE 2>&1; then
+    echo "failed during search"
+    exit -1
+fi
